apiVersion: apps/v1
kind: Rollout
metadata:
  name: tetris-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tetris
  template:
    metadata:
      labels:
        app: tetris
    spec:
      containers:
      - name: tetris
        image: nasi101/tetris
        ports:
        - containerPort: 80
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      stableService: tetris-stable
      canaryService: tetris-canary
      steps:
      - setWeight: 20
      - pause:
          duration: "1m" # 1 hour
      - setWeight: 60
      - pause: {} # pause indefinitely
